"""
Live DataHub Metadata Publisher for FleetGuard AI.

Automatically publishes live vehicle telemetry metadata, schemas, and lineage graph
from the active application backend directly to DataHub GMS.
"""

from __future__ import annotations

import logging
import os
import json
import urllib.request
import importlib
from typing import Any, Dict, List, Optional

logger = logging.getLogger("fleetguard.live_publisher")


def _get_gms_url() -> str:
    return os.getenv("DATAHUB_GMS_URL", "http://localhost:8080").rstrip("/")


def publish_live_fleet_metadata() -> Dict[str, Any]:
    """
    Emits live fleet dataset schemas, ML model entities, and lineage graph
    directly to DataHub GMS from the live application server.
    """
    gms_url = _get_gms_url()
    logger.info(f"Publishing live fleet metadata from API server to DataHub GMS at: {gms_url}")

    # Method 1: Python SDK if acryl-datahub installed
    try:
        mcp_mod = importlib.import_module("datahub.emitter.mcp")
        graph_mod = importlib.import_module("datahub.ingestion.graph.client")
        config_mod = importlib.import_module("datahub.ingestion.graph.config")
        schema_mod = importlib.import_module("datahub.metadata.schema_classes")

        MetadataChangeProposalWrapper = getattr(mcp_mod, "MetadataChangeProposalWrapper")
        DataHubGraph = getattr(graph_mod, "DataHubGraph")
        DatahubClientConfig = getattr(config_mod, "DatahubClientConfig")
        DatasetPropertiesClass = getattr(schema_mod, "DatasetPropertiesClass")
        OwnershipClass = getattr(schema_mod, "OwnershipClass")
        OwnerClass = getattr(schema_mod, "OwnerClass")
        OwnershipTypeClass = getattr(schema_mod, "OwnershipTypeClass")
        UpstreamLineageClass = getattr(schema_mod, "UpstreamLineageClass")
        UpstreamClass = getattr(schema_mod, "UpstreamClass")
        AuditStampClass = getattr(schema_mod, "AuditStampClass")
        SchemaMetadataClass = getattr(schema_mod, "SchemaMetadataClass")
        SchemaFieldClass = getattr(schema_mod, "SchemaFieldClass")
        SchemaFieldDataTypeClass = getattr(schema_mod, "SchemaFieldDataTypeClass")
        NumberTypeClass = getattr(schema_mod, "NumberTypeClass")

        graph = DataHubGraph(DatahubClientConfig(server=gms_url))

        # 1. Main Feature Dataset
        ds_mcp = MetadataChangeProposalWrapper(
            entityType="dataset",
            entityUrn="urn:li:dataset:(urn:li:dataPlatform:kafka,vehicle_health_features,PROD)",
            aspect=DatasetPropertiesClass(
                name="vehicle_health_features",
                description="Live real-time 15 EV telemetry feature dataset generated by FleetGuard Platform.",
                customProperties={
                    "fleet_size": "15",
                    "update_frequency": "10Hz / 100ms",
                    "domain": "fleet_reliability",
                    "live_source": "FleetGuard API Server",
                },
            ),
        )
        graph.emit(ds_mcp)

        # 2. Schema Aspect
        schema_mcp = MetadataChangeProposalWrapper(
            entityType="dataset",
            entityUrn="urn:li:dataset:(urn:li:dataPlatform:kafka,vehicle_health_features,PROD)",
            aspect=SchemaMetadataClass(
                schemaName="LiveVehicleTelemetry",
                platform="urn:li:dataPlatform:kafka",
                version=1,
                hash="",
                platformSchema={},
                fields=[
                    SchemaFieldClass(fieldPath="battery_pct", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="HV traction battery state-of-charge %"),
                    SchemaFieldClass(fieldPath="temperature_c", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="Battery thermal temperature (°C)"),
                    SchemaFieldClass(fieldPath="vibration_hz", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="LiDAR mount vibration frequency (Hz)"),
                    SchemaFieldClass(fieldPath="health_score", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="Composite vehicle health index (0-100%)"),
                    SchemaFieldClass(fieldPath="maintenance_rul_pct", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="Predicted Remaining Useful Life (%)"),
                ],
            ),
        )
        graph.emit(schema_mcp)

        # 3. Ownership Aspect
        owner_mcp = MetadataChangeProposalWrapper(
            entityType="dataset",
            entityUrn="urn:li:dataset:(urn:li:dataPlatform:kafka,vehicle_health_features,PROD)",
            aspect=OwnershipClass(
                owners=[OwnerClass(owner="urn:li:corpuser:fleet_ops", type=OwnershipTypeClass.TECHNICAL_OWNER)]
            ),
        )
        graph.emit(owner_mcp)

        # 4. ML Models & Lineage
        for model_name, model_desc in [
            ("rul_predictor_model", "Live XGBoost Remaining Useful Life predictor"),
            ("anomaly_detector_model", "Live Isolation Forest Telemetry anomaly detector"),
        ]:
            model_urn = f"urn:li:dataset:(urn:li:dataPlatform:ml,{model_name},PROD)"
            graph.emit(
                MetadataChangeProposalWrapper(
                    entityType="dataset",
                    entityUrn=model_urn,
                    aspect=DatasetPropertiesClass(name=model_name, description=model_desc),
                )
            )
            graph.emit(
                MetadataChangeProposalWrapper(
                    entityType="dataset",
                    entityUrn=model_urn,
                    aspect=UpstreamLineageClass(
                        upstreams=[
                            UpstreamClass(
                                dataset="urn:li:dataset:(urn:li:dataPlatform:kafka,vehicle_health_features,PROD)",
                                type="TRANSFORMED",
                                auditStamp=AuditStampClass(time=1000, actor="urn:li:corpuser:fleet_ops"),
                            )
                        ]
                    ),
                )
            )

        return {"success": True, "mode": "live_sdk_emitter", "gms_url": gms_url}

    except Exception as err:
        logger.warning(f"SDK metadata publishing offline ({err}). Trying REST API fallback...")

    # Method 2: REST GMS API Fallback
    try:
        token = os.getenv("DATAHUB_GMS_TOKEN")
        urn = "urn:li:dataset:(urn:li:dataPlatform:kafka,vehicle_health_features,PROD)"
        payload = {
            "proposal": {
                "entityType": "dataset",
                "entityUrn": urn,
                "aspectName": "datasetProperties",
                "aspect": {
                    "json": json.dumps({
                        "name": "vehicle_health_features",
                        "description": "Live real-time 15 EV telemetry feature set from FleetGuard Platform",
                        "customProperties": {"fleet_size": "15", "live_source": "FleetGuard Web App"},
                    })
                },
            }
        }
        data_bytes = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(f"{gms_url}/aspects?action=ingestProposal", data=data_bytes, headers={"Content-Type": "application/json"})
        if token:
            req.add_header("Authorization", f"Bearer {token}")
        with urllib.request.urlopen(req, timeout=3) as resp:
            if resp.status in (200, 201):
                return {"success": True, "mode": "live_rest_api", "gms_url": gms_url}
    except Exception as ex:
        logger.warning(f"REST metadata publishing fallback offline: {ex}")

    return {"success": False, "mode": "offline", "gms_url": gms_url, "error": "DataHub GMS unreachable"}
