"""
Live DataHub Metadata Publisher for FleetGuard AI.

Automatically publishes live vehicle telemetry metadata, schemas, and lineage graph
from the active application backend directly to DataHub GMS.
"""

from __future__ import annotations

import logging
import os
import json
import urllib.request
import importlib
from typing import Any, Dict, List, Optional

logger = logging.getLogger("fleetguard.live_publisher")


def _get_gms_url() -> str:
    return os.getenv("DATAHUB_GMS_URL", "http://localhost:8080").rstrip("/")


def publish_live_fleet_metadata() -> Dict[str, Any]:
    """
    Emits live fleet dataset schemas, ML model entities, and lineage graph
    directly to DataHub GMS from the live application server.
    """
    gms_url = _get_gms_url()
    logger.info(f"Publishing live fleet metadata from API server to DataHub GMS at: {gms_url}")

    urn = "urn:li:dataset:(urn:li:dataPlatform:kafka,vehicle_health_features,PROD)"

    # Method 1: Python SDK if acryl-datahub installed
    try:
        mcp_mod = importlib.import_module("datahub.emitter.mcp")
        graph_mod = importlib.import_module("datahub.ingestion.graph.client")
        config_mod = importlib.import_module("datahub.ingestion.graph.config")
        schema_mod = importlib.import_module("datahub.metadata.schema_classes")

        MetadataChangeProposalWrapper = getattr(mcp_mod, "MetadataChangeProposalWrapper")
        DataHubGraph = getattr(graph_mod, "DataHubGraph")
        DatahubClientConfig = getattr(config_mod, "DatahubClientConfig")
        DatasetPropertiesClass = getattr(schema_mod, "DatasetPropertiesClass")
        OwnershipClass = getattr(schema_mod, "OwnershipClass")
        OwnerClass = getattr(schema_mod, "OwnerClass")
        OwnershipTypeClass = getattr(schema_mod, "OwnershipTypeClass")
        UpstreamLineageClass = getattr(schema_mod, "UpstreamLineageClass")
        UpstreamClass = getattr(schema_mod, "UpstreamClass")
        AuditStampClass = getattr(schema_mod, "AuditStampClass")
        SchemaMetadataClass = getattr(schema_mod, "SchemaMetadataClass")
        SchemaFieldClass = getattr(schema_mod, "SchemaFieldClass")
        SchemaFieldDataTypeClass = getattr(schema_mod, "SchemaFieldDataTypeClass")
        NumberTypeClass = getattr(schema_mod, "NumberTypeClass")
        OtherSchemaClass = getattr(schema_mod, "OtherSchemaClass")

        graph = DataHubGraph(DatahubClientConfig(server=gms_url))

        # 1. Main Feature Dataset
        ds_mcp = MetadataChangeProposalWrapper(
            entityType="dataset",
            entityUrn=urn,
            aspect=DatasetPropertiesClass(
                name="vehicle_health_features",
                description="Live real-time 15 EV telemetry feature dataset generated by FleetGuard Platform.",
                customProperties={
                    "fleet_size": "15",
                    "update_frequency": "10Hz / 100ms",
                    "domain": "fleet_reliability",
                    "live_source": "FleetGuard API Server",
                },
            ),
        )
        graph.emit(ds_mcp)

        # 2. Schema Aspect with proper platformSchema and nativeDataType
        other_schema = OtherSchemaClass(rawSchema="")
        fields = [
            SchemaFieldClass(fieldPath="battery_pct", nativeDataType="NUMBER", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="HV traction battery state-of-charge %"),
            SchemaFieldClass(fieldPath="battery_temperature", nativeDataType="NUMBER", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="Battery pack temperature in Celsius (°C)"),
            SchemaFieldClass(fieldPath="vibration_hz", nativeDataType="NUMBER", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="LiDAR mount vibration frequency (Hz)"),
            SchemaFieldClass(fieldPath="health_score", nativeDataType="NUMBER", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="Composite vehicle health index (0-100%)"),
            SchemaFieldClass(fieldPath="maintenance_rul_pct", nativeDataType="NUMBER", type=SchemaFieldDataTypeClass(type=NumberTypeClass()), description="Predicted Remaining Useful Life (%)"),
        ]
        schema_mcp = MetadataChangeProposalWrapper(
            entityType="dataset",
            entityUrn=urn,
            aspect=SchemaMetadataClass(
                schemaName="VehicleHealthFeatures",
                platform="urn:li:dataPlatform:kafka",
                version=0,
                hash="",
                platformSchema=other_schema,
                fields=fields,
            ),
        )
        graph.emit(schema_mcp)

        # 3. Ownership Aspect
        owner_mcp = MetadataChangeProposalWrapper(
            entityType="dataset",
            entityUrn=urn,
            aspect=OwnershipClass(
                owners=[OwnerClass(owner="urn:li:corpuser:fleet_ops", type=OwnershipTypeClass.TECHNICAL_OWNER)]
            ),
        )
        graph.emit(owner_mcp)

        # 4. ML Models & Lineage
        for model_name, model_desc in [
            ("rul_predictor_model", "Live XGBoost Remaining Useful Life predictor"),
            ("anomaly_detector_model", "Live Isolation Forest Telemetry anomaly detector"),
        ]:
            model_urn = f"urn:li:dataset:(urn:li:dataPlatform:ml,{model_name},PROD)"
            graph.emit(
                MetadataChangeProposalWrapper(
                    entityType="dataset",
                    entityUrn=model_urn,
                    aspect=DatasetPropertiesClass(name=model_name, description=model_desc),
                )
            )
            graph.emit(
                MetadataChangeProposalWrapper(
                    entityType="dataset",
                    entityUrn=model_urn,
                    aspect=UpstreamLineageClass(
                        upstreams=[
                            UpstreamClass(
                                dataset=urn,
                                type="TRANSFORMED",
                                auditStamp=AuditStampClass(time=1000, actor="urn:li:corpuser:fleet_ops"),
                            )
                        ]
                    ),
                )
            )

        return {"success": True, "mode": "live_sdk_emitter", "gms_url": gms_url}

    except Exception as err:
        logger.warning(f"SDK metadata publishing failed/offline ({err}). Ingesting via REST GMS API...")

    # Method 2: Direct REST GMS API Proposals (Guaranteed Fallback)
    try:
        token = os.getenv("DATAHUB_GMS_TOKEN")
        headers = {"Content-Type": "application/json"}
        if token:
            headers["Authorization"] = f"Bearer {token}"

        # A. datasetProperties
        p1 = {
            "proposal": {
                "entityType": "dataset",
                "entityUrn": urn,
                "aspectName": "datasetProperties",
                "changeType": "UPSERT",
                "aspect": {
                    "contentType": "application/json",
                    "value": json.dumps({
                        "name": "vehicle_health_features",
                        "description": "Live real-time 15 EV telemetry feature set from FleetGuard Platform",
                        "customProperties": {"fleet_size": "15", "live_source": "FleetGuard Web App"},
                    })
                },
            }
        }
        req1 = urllib.request.Request(f"{gms_url}/aspects?action=ingestProposal", data=json.dumps(p1).encode("utf-8"), headers=headers)
        with urllib.request.urlopen(req1, timeout=3) as resp:
            pass

        # B. schemaMetadata REST API Proposal
        schema_dict = {
            "schemaName": "VehicleHealthFeatures",
            "platform": "urn:li:dataPlatform:kafka",
            "version": 0,
            "created": {"time": 0, "actor": "urn:li:corpuser:unknown"},
            "lastModified": {"time": 0, "actor": "urn:li:corpuser:unknown"},
            "hash": "",
            "platformSchema": {
                "com.linkedin.pegasus2avro.schema.OtherSchema": {
                    "rawSchema": ""
                }
            },
            "fields": [
                {
                    "fieldPath": "battery_pct",
                    "nullable": False,
                    "description": "HV traction battery state of charge %",
                    "type": {"type": {"com.linkedin.pegasus2avro.schema.NumberType": {}}},
                    "nativeDataType": "NUMBER"
                },
                {
                    "fieldPath": "battery_temperature",
                    "nullable": False,
                    "description": "Battery pack temperature in Celsius (°C)",
                    "type": {"type": {"com.linkedin.pegasus2avro.schema.NumberType": {}}},
                    "nativeDataType": "NUMBER"
                },
                {
                    "fieldPath": "vibration_hz",
                    "nullable": False,
                    "description": "LiDAR mount vibration frequency (Hz)",
                    "type": {"type": {"com.linkedin.pegasus2avro.schema.NumberType": {}}},
                    "nativeDataType": "NUMBER"
                },
                {
                    "fieldPath": "health_score",
                    "nullable": False,
                    "description": "Composite vehicle health index (0-100%)",
                    "type": {"type": {"com.linkedin.pegasus2avro.schema.NumberType": {}}},
                    "nativeDataType": "NUMBER"
                },
                {
                    "fieldPath": "maintenance_rul_pct",
                    "nullable": False,
                    "description": "Predicted Remaining Useful Life (%)",
                    "type": {"type": {"com.linkedin.pegasus2avro.schema.NumberType": {}}},
                    "nativeDataType": "NUMBER"
                }
            ]
        }
        p2 = {
            "proposal": {
                "entityType": "dataset",
                "entityUrn": urn,
                "aspectName": "schemaMetadata",
                "changeType": "UPSERT",
                "aspect": {
                    "contentType": "application/json",
                    "value": json.dumps(schema_dict)
                },
            }
        }
        req2 = urllib.request.Request(f"{gms_url}/aspects?action=ingestProposal", data=json.dumps(p2).encode("utf-8"), headers=headers)
        with urllib.request.urlopen(req2, timeout=3) as resp:
            pass

        return {"success": True, "mode": "live_rest_api", "gms_url": gms_url}

    except Exception as ex:
        logger.warning(f"REST metadata publishing fallback failed: {ex}")

    return {"success": False, "mode": "offline", "gms_url": gms_url, "error": "DataHub GMS unreachable"}
